- name: play with variables task level
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Shiva"
    Duration: "110hrs"
  tasks: 
- name: check variables
  vars: 
    Course: "Devops with AWS"
      ansible.builtin.debug:
      msg: "Hi learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
