- name: loops
  hosts: localhost
  become: yes
  tasks: 
  - name: print persons
    ansible.builtin.package:
      name: "{{item}}" #item is default keyword in ansible
      state: present
    loop:
    - sql
    - postfix
    - git
    